[package]
name = "incomudon-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
incomudon-core = { path = "../incomudon-core" }
incomudon-crypto = { path = "../incomudon-crypto" }
incomudon-protocol = { path = "../incomudon-protocol" }
rand.workspace = true
thiserror.workspace = true
